[package]
name = "dep_template"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
serde_json.workspace = true
handlebars = "6.3.2"
minijinja = "2.14.0"
tera = "1.20.1"
common_core = { path = "../../common/common_core" }
common_macros = { path = "../../common/common_macros" }
linkme = "0.3.35"