[package]
name = "dep_template"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
serde_json.workspace = true
handlebars = "6.3.2"
minijinja = "2.14.0"
tera = "1.20.1"
wjj-std = { path = "/Users/wjj/projects/wjj-std/wjj-std", features = ["error", "app"] }