[package]
name = "dep_orm_sea_orm"
version = "0.0.1"
edition = "2024"

[dependencies]
tokio.workspace = true
sea-orm = { version = "1.1.19", features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
dotenvy = "0.15.7"