[package]
name = "dep_serialization"
version = "0.0.1"
edition = "2024"

[dependencies]
serde = { version = "1.0.228",  features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34+deprecated"
jaq-parse = "1.0.3"